//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double NetConfig_SynapsePermanenceThreshold {
            get {
                return ((double)(this["NetConfig_SynapsePermanenceThreshold"]));
            }
            set {
                this["NetConfig_SynapsePermanenceThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double NetConfig_SynapsePermanenceIncrease {
            get {
                return ((double)(this["NetConfig_SynapsePermanenceIncrease"]));
            }
            set {
                this["NetConfig_SynapsePermanenceIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double NetConfig_SynapsePermanenceDecrease {
            get {
                return ((double)(this["NetConfig_SynapsePermanenceDecrease"]));
            }
            set {
                this["NetConfig_SynapsePermanenceDecrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NetConfig_DendriteActivationThresholdProximal {
            get {
                return ((int)(this["NetConfig_DendriteActivationThresholdProximal"]));
            }
            set {
                this["NetConfig_DendriteActivationThresholdProximal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NetConfig_DendriteActivationThresholdBasal {
            get {
                return ((int)(this["NetConfig_DendriteActivationThresholdBasal"]));
            }
            set {
                this["NetConfig_DendriteActivationThresholdBasal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NetConfig_DendriteActivationThresholdApical {
            get {
                return ((int)(this["NetConfig_DendriteActivationThresholdApical"]));
            }
            set {
                this["NetConfig_DendriteActivationThresholdApical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NetConfig_ColumnStimulusThreshold {
            get {
                return ((int)(this["NetConfig_ColumnStimulusThreshold"]));
            }
            set {
                this["NetConfig_ColumnStimulusThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double NetConfig_ZoneSizePercProximal {
            get {
                return ((double)(this["NetConfig_ZoneSizePercProximal"]));
            }
            set {
                this["NetConfig_ZoneSizePercProximal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double NetConfig_ZoneCoveragePercProximal {
            get {
                return ((double)(this["NetConfig_ZoneCoveragePercProximal"]));
            }
            set {
                this["NetConfig_ZoneCoveragePercProximal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double NetConfig_ZoneSizePercBasal {
            get {
                return ((double)(this["NetConfig_ZoneSizePercBasal"]));
            }
            set {
                this["NetConfig_ZoneSizePercBasal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double NetConfig_ZoneCoveragePercBasal {
            get {
                return ((double)(this["NetConfig_ZoneCoveragePercBasal"]));
            }
            set {
                this["NetConfig_ZoneCoveragePercBasal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double NetConfig_ZoneSizePercApical {
            get {
                return ((double)(this["NetConfig_ZoneSizePercApical"]));
            }
            set {
                this["NetConfig_ZoneSizePercApical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double NetConfig_ZoneCoveragePercApical {
            get {
                return ((double)(this["NetConfig_ZoneCoveragePercApical"]));
            }
            set {
                this["NetConfig_ZoneCoveragePercApical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NetConfig_NumCellsInColumn {
            get {
                return ((int)(this["NetConfig_NumCellsInColumn"]));
            }
            set {
                this["NetConfig_NumCellsInColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double NetConfig_ColumnsTopPercentile {
            get {
                return ((double)(this["NetConfig_ColumnsTopPercentile"]));
            }
            set {
                this["NetConfig_ColumnsTopPercentile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NetConfig_NumEpochsToTrain {
            get {
                return ((int)(this["NetConfig_NumEpochsToTrain"]));
            }
            set {
                this["NetConfig_NumEpochsToTrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NetConfig_ActivationDensityInterval {
            get {
                return ((int)(this["NetConfig_ActivationDensityInterval"]));
            }
            set {
                this["NetConfig_ActivationDensityInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double NetConfig_ActivationDensityTarget {
            get {
                return ((double)(this["NetConfig_ActivationDensityTarget"]));
            }
            set {
                this["NetConfig_ActivationDensityTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefreshArea1 {
            get {
                return ((bool)(this["RefreshArea1"]));
            }
            set {
                this["RefreshArea1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefreshArea2 {
            get {
                return ((bool)(this["RefreshArea2"]));
            }
            set {
                this["RefreshArea2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RefreshArea3 {
            get {
                return ((bool)(this["RefreshArea3"]));
            }
            set {
                this["RefreshArea3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SparsenessParamSearchEnable {
            get {
                return ((bool)(this["SparsenessParamSearchEnable"]));
            }
            set {
                this["SparsenessParamSearchEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string LastFileOpen {
            get {
                return ((string)(this["LastFileOpen"]));
            }
            set {
                this["LastFileOpen"] = value;
            }
        }
    }
}
